name: Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Go 1.11 and Test
        uses: cedrickring/golang-action/go1.11@1.6.0
        env:
          IMPORT: "ProspectOne/perfops-cli"

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
      - uses: actions/checkout@v1
      - name: install and build
        run: |
          npm install
      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
          NPM_TOKEN: 0000-0000-0000-0000

      - run: go get -v -d ./
      - run: bash hack/build-all.sh

      - name: Publish packages
        run: bash hack/build-pkgs.sh
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
