name: Release version

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          prerelease: false
          automatic_release_tag: latest
