name: Publish release

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
